---
- name: tomcat config
  hosts: all
  become: true
  vars:
    directory: /usr/local

  tasks:

  - name: firewalld stop
    service:
      name: firewalld
      state: stopped
      enabled: False
    when: ansible_cmdline['BOOT_IMAGE']== '/vmlinuz-3.10.0-1160.el7.x86_64'

  - name: install wget
    yum:
      name: wget
      state: present

  - name: install jdk 11
    yum:
      name: java-11-openjdk

  - name: install jdk11-devel
    yum:
      name: java-11-openjdk-devel

  - name: tomcat install
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz
      dest: "{{ directory }}"

  - name: extract tomcat package
    unarchive:
      src: "/usr/local/apache-tomcat-9.0.50.tar.gz"
      dest: "{{ directory }}"
      remote_src: yes

  - name: copy server.xml
    copy:
      src: /ansible/file/server.xml
      dest: /usr/local/apache-tomcat-9.0.50/conf/

  - name: install mysql
    yum:
      name: mysql
      state: present
  - name: mysql-connector-copy
    copy:
      src: /ansible/file/mysql-connector-java-8.0.24.jar
      dest: /usr/local/apache-tomcat-9.0.50/lib

  - name: copy war file
    copy:
      src: /ansible/file/web.war
      dest: /usr/local/apache-tomcat-9.0.50/webapps/


  - name: tomcat start
    command: nohup /usr/local/apache-tomcat-9.0.50/bin/startup.sh

  - name: tomcat shutdown
    command: nohup /usr/local/apache-tomcat-9.0.50/bin/shutdown.sh


  - name: copy ipfile
    copy:
      src: /ansible/file/ip.jsp
      dest: /usr/local/apache-tomcat-9.0.50/webapps/

  - name: tomcat start
    command: nohup /usr/local/apache-tomcat-9.0.50/bin/startup.sh

